# Generated by Django 5.1.6 on 2025-03-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsetuser',
            name='DOB',
            field=models.DateField(default=None),
        ),
    ]
