# Generated by Django 5.1.6 on 2025-03-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0002_alter_allsetuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allsetuser',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
