# Generated by Django 5.1.6 on 2025-03-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0003_alter_allsetuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsetuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
